
### user
#get users
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzVhYzUyNzhlNjFjNjJmMjAyNWYwNmIiLCJ1c2VybmFtZSI6ImZhdGlyIiwidXNlcmVtYWlsIjoiZmF0aXJAZ21haWwuY29tIiwiaWF0IjoxNzM0NDM4Njg4LCJleHAiOjE3MzQ0Mzg3NDh9._kKxcO9dCpD0rtZ0m2HWsuZSQQRBOh_RK-28pwVWlQs


###
#register
POST http://localhost:8080/api/user
Content-Type: application/json

{
    "username": "Admin1",
    "useremail": "admincafe@test.com",
    "password": "admincafe123",
    "role": "admin"
}


###
#login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "useremail": "fatir@gmail.com",
    "password": "fatir123"
}


###
#logout
DELETE http://localhost:8080/api/logout


###
#delete user
DELETE http://localhost:8080/api/user/675ab34c0400dfc13b192445

###
#refresh token
GET http://localhost:8080/api/token






### comment
GET http://localhost:8080/api/comment
###

POST http://localhost:8080/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzVhYzUyNzhlNjFjNjJmMjAyNWYwNmIiLCJpYXQiOjE3MzQyNDA5NjIsImV4cCI6MTczNDI0MTAyMn0.f5YlwElCq2K5ZN3sHiLBCjlRNzYQM04xRnluF_UJQeU

{
    "comment": "fatir commented"
}
###
DELETE http://localhost:8080/api/comment/675abcd59c64c261cafcf8a6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzVhYzUyNzhlNjFjNjJmMjAyNWYwNmIiLCJpYXQiOjE3MzQyNDE0ODUsImV4cCI6MTczNDI0MTU0NX0.W0WMPjiUhZH2TsFLqkkObMrBN840D9sYZ9hCt4AofUs





### order
#create transaction
POST http://localhost:8080/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzVhYzUyNzhlNjFjNjJmMjAyNWYwNmIiLCJpYXQiOjE3MzQyNTQyOTgsImV4cCI6MTczNDI1NDM1OH0.iTdSr4BjV9RH-a57hYnTRV1E6EUiNgTVMOshO184iIk

{
    "products":[
        {
            "productId": "6758099828363f5fd538158a",
            "quantity": 1,
            "price": 18000
        }
    ],
    "totalAmount": 18000
}